export const loginStyles = {
  wrapper: {
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "#f0f2f5",
    fontFamily: "system-ui, sans-serif",
    padding: "20px",
    boxSizing: "border-box",
  },
  card: {
    background: "#ffffff",
    borderRadius: "12px",
    padding: "32px 28px",
    width: "100%",
    maxWidth: "360px",
    boxShadow: "0 2px 12px rgba(0,0,0,0.1)",
    border: "1px solid #e8eaed",
    display: "flex",
    flexDirection: "column",
  },
  title: {
    fontSize: "18px",
    fontWeight: 700,
    color: "#1a1a1a",
    textAlign: "center",
  },
  subtitle: {
    fontSize: "13px",
    color: "#5f6368",
    textAlign: "center",
    marginTop: "4px",
    marginBottom: "22px",
  },
  label: {
    fontSize: "13px",
    fontWeight: 600,
    color: "#3c4043",
    marginBottom: "6px",
    marginTop: "12px",
  },
  input: {
    border: "1px solid #dadce0",
    borderRadius: "6px",
    padding: "10px 12px",
    fontSize: "14px",
    outline: "none",
    fontFamily: "system-ui, sans-serif",
  },
  error: {
    color: "#b3261e",
    fontSize: "12.5px",
    marginTop: "12px",
    textAlign: "center",
  },
  button: {
    marginTop: "22px",
    background: "#1f4e3d",
    color: "#ffffff",
    border: "none",
    padding: "11px 22px",
    borderRadius: "6px",
    fontSize: "14px",
    fontWeight: 600,
    cursor: "pointer",
  },
};
