import { FONT } from "../constants";

export const styles = {
  pageWrapper: {
    background: "#f0f2f5",
    minHeight: "100vh",
    padding: "20px 0 60px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    fontFamily: FONT,
  },
  toolbarContainer: {
    width: "210mm",
    maxWidth: "94vw",
    background: "#ffffff",
    borderRadius: "10px",
    padding: "18px 20px",
    marginBottom: "20px",
    boxShadow: "0 1px 3px rgba(0,0,0,0.08)",
    border: "1px solid #e8eaed",
    fontFamily: "system-ui, sans-serif",
  },
  toolbarHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "16px",
    gap: "12px",
  },
  toolbarTitle: { fontSize: "16px", fontWeight: 700, color: "#1a1a1a" },
  toolbarSubtitle: { fontSize: "12.5px", color: "#5f6368", marginTop: "2px" },
  btnPrint: {
    background: "#1f4e3d",
    color: "#ffffff",
    border: "none",
    padding: "11px 22px",
    borderRadius: "6px",
    fontSize: "14px",
    fontWeight: 600,
    cursor: "pointer",
    whiteSpace: "nowrap",
    flexShrink: 0,
  },
  tabSection: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    marginBottom: "12px",
    paddingBottom: "12px",
    borderBottom: "1px solid #f0f0f0",
  },
  tabWrapper: {
    display: "flex",
    flex: 1,
    gap: "6px",
    overflowX: "auto",
    padding: "2px 0",
    flexWrap: "nowrap",
  },
  tabBtn: {
    background: "#f8f9fa",
    color: "#3c4043",
    border: "1px solid #dadce0",
    padding: "7px 14px",
    borderRadius: "16px",
    fontSize: "13px",
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  tabBtnActive: {
    background: "#1f4e3d",
    color: "#ffffff",
    border: "1px solid #1f4e3d",
    fontWeight: 600,
  },
  addBtn: {
    background: "#eef4f1",
    color: "#1f4e3d",
    border: "1px dashed #1f4e3d",
    padding: "7px 14px",
    borderRadius: "16px",
    fontSize: "13px",
    fontWeight: 600,
    cursor: "pointer",
    whiteSpace: "nowrap",
    flexShrink: 0,
  },
  quickActions: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    flexWrap: "wrap",
  },
  btnGhost: {
    background: "#ffffff",
    color: "#3c4043",
    border: "1px solid #dadce0",
    padding: "7px 14px",
    borderRadius: "6px",
    fontSize: "13px",
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  moreWrapper: { position: "relative", marginLeft: "auto" },
  moreMenu: {
    position: "absolute",
    top: "calc(100% + 6px)",
    right: 0,
    background: "#ffffff",
    border: "1px solid #e0e0e0",
    borderRadius: "8px",
    boxShadow: "0 4px 16px rgba(0,0,0,0.12)",
    minWidth: "230px",
    padding: "6px",
    zIndex: 10,
    display: "flex",
    flexDirection: "column",
  },
  moreMenuItem: {
    background: "transparent",
    border: "none",
    textAlign: "left",
    padding: "9px 10px",
    fontSize: "13px",
    color: "#3c4043",
    cursor: "pointer",
    borderRadius: "5px",
    width: "100%",
    boxSizing: "border-box",
  },
  moreMenuDivider: { height: "1px", background: "#eee", margin: "4px 0" },

  paper: {
    background: "#ffffff",
    width: "210mm",
    minHeight: "297mm",
    padding: "16mm 18mm",
    boxSizing: "border-box",
    boxShadow: "0 2px 8px rgba(0,0,0,0.1)",
    color: "#1a1a1a",
    marginBottom: "24px",
    position: "relative",
    overflow: "hidden",
  },
  paperContent: { position: "relative", zIndex: 1 },
  watermarkWrapper: {
    position: "absolute",
    top: "40%",
    left: "60%",
    transform: "translate(-50%, -50%)",
    width: "78%",
    zIndex: 0,
    pointerEvents: "none",
    opacity: 0.14,
  },
  headerRow: {
    display: "flex",
    justifyContent: "space-between",
    gap: "20px",
    fontSize: "13px",
    lineHeight: 1.45,
  },
  headerLeft: { flex: 1.3, textAlign: "left" },
  headerRight: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    textAlign: "left",
  },
  staticLine: {
    display: "flex",
    gap: "4px",
    alignItems: "baseline",
    width: "100%",
    textAlign: "left",
  },
  staticLabel: { minWidth: "112px", fontWeight: 600, whiteSpace: "nowrap" },
  inlineInput: {
    border: "none",
    borderBottom: "1px dotted #999",
    outline: "none",
    fontSize: "13.5px",
    flex: 1,
    minWidth: 0,
    padding: "1px 4px",
    background: "transparent",
    fontFamily: FONT,
  },
  divider: {
    borderTop: "2px solid #1a1a1a",
    marginTop: "12px",
    marginBottom: "6px",
  },
  title: {
    textAlign: "center",
    fontSize: "19px",
    fontWeight: 700,
    letterSpacing: "1px",
    margin: "8px 0 14px",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: "13.5px",
    marginBottom: "16px",
  },
  th: {
    border: "1px solid #1a1a1a",
    padding: "8px 10px",
    background: "#f5f5f4",
    fontWeight: 700,
    textAlign: "left",
  },
  thNo: { width: "42px", textAlign: "center" },
  thNilai: { width: "120px", textAlign: "center" },
  thAction: { width: "30px", border: "none" },
  td: { border: "1px solid #1a1a1a", padding: "4px 8px" },
  tdNo: { textAlign: "center" },
  tdNilai: { textAlign: "center" },
  tdAction: { border: "none", textAlign: "center" },
  cellInput: {
    width: "100%",
    border: "none",
    outline: "none",
    fontSize: "13.5px",
    padding: "5px 2px",
    background: "transparent",
    fontFamily: FONT,
    boxSizing: "border-box",
  },
  btnRemove: {
    border: "none",
    background: "#f5ecec",
    color: "#8a1f1f",
    width: "22px",
    height: "22px",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "14px",
    lineHeight: 1,
  },
  midSection: {
    display: "flex",
    marginBottom: "12px",
    gap: "20px",
  },
  attendanceBlock: { width: "48%" },
  blockLabel: {
    fontWeight: 700,
    fontSize: "13.5px",
    marginBottom: "6px",
    textAlign: "left",
  },
  attendanceBox: {
    border: "1px solid #1a1a1a",
    padding: "10px 12px",
    display: "flex",
    flexDirection: "column",
    boxSizing: "border-box",
  },
  attendanceLine: {
    display: "flex",
    alignItems: "baseline",
    fontSize: "13.5px",
    textAlign: "left",
    width: "100%",
    marginBottom: "6px",
  },
  attendanceLabel: {
    minWidth: "125px",
    textAlign: "left",
    flexShrink: 0,
    whiteSpace: "nowrap",
  },
  attendanceColon: { marginRight: "6px" },
  attendanceInput: {
    width: "45px",
    border: "none",
    borderBottom: "1px dotted #999",
    outline: "none",
    textAlign: "center",
    fontSize: "13.5px",
    background: "transparent",
    fontFamily: FONT,
    marginRight: "6px",
  },
  attendanceUnit: { flexShrink: 0 },

  peringkatBlock: {
    width: "48%",
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
  },
  peringkatLine: {
    display: "flex",
    alignItems: "baseline",
    fontSize: "13.5px",
    textAlign: "left",
    width: "100%",
    border: "1px solid #1a1a1a",
    padding: "10px 12px",
    boxSizing: "border-box",
    minHeight: "80px",
    flex: 1,
  },
  peringkatLabel: {
    minWidth: "80px",
    textAlign: "left",
    flexShrink: 0,
    whiteSpace: "nowrap",
  },
  peringkatColon: { marginRight: "6px" },
  peringkatInput: {
    width: "100%",
    border: "none",
    borderBottom: "1px dotted #999",
    outline: "none",
    fontSize: "13.5px",
    padding: "4px 2px",
    background: "transparent",
    fontFamily: FONT,
    textAlign: "center",
    flex: 1,
  },

  noteBlock: { marginBottom: "10px" },
  noteBox: {
    width: "100%",
    minHeight: "28px",
    border: "1px solid #1a1a1a",
    padding: "10px 12px",
    fontSize: "13.5px",
    outline: "none",
    resize: "none",
    overflow: "hidden",
    boxSizing: "border-box",
    fontFamily: FONT,
    display: "block",
  },
  dateRow: {
    display: "flex",
    justifyContent: "flex-end",
    marginTop: "14px",
    marginBottom: "10px",
    fontSize: "13.5px",
  },
  dateLine: { display: "flex", alignItems: "baseline", gap: "2px" },
  dateInput: {
    border: "none",
    borderBottom: "1px dotted #999",
    outline: "none",
    fontSize: "13.5px",
    textAlign: "center",
    background: "transparent",
    fontFamily: FONT,
  },
  signRow: {
    display: "flex",
    justifyContent: "space-between",
    marginTop: "16px",
    fontSize: "13.5px",
    width: "100%",
  },
  signCol: {
    width: "33.33%",
    boxSizing: "border-box",
    textAlign: "center",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    paddingLeft: "8px",
    paddingRight: "8px",
  },
  signHeaderBlock: {
    height: "40px",
    width: "100%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    lineHeight: "20px",
  },
  signHeader: { fontWeight: 600 },
  signRole: { marginTop: "0px" },
  signSpace: { height: "36px", flexShrink: 0, width: "100%" },
  signInput: {
    border: "none",
    borderTop: "1px solid #1a1a1a",
    outline: "none",
    textAlign: "center",
    fontSize: "13.5px",
    width: "100%",
    maxWidth: "170px",
    padding: "4px 0 0",
    background: "transparent",
    fontFamily: FONT,
    boxSizing: "border-box",
  },
};
